cats_99/config/routes.rb
Rails.application.routes.draw do
  resources :cats
end

cats_99/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

cats_99/app/models/cat.rb
class Cat < ApplicationRecord
  COLORS = ['Red', "Green", "Blue", "Yellow", "Purple", "Orange", "Black", "White", "Grey"]
  
  validates :birth_date, :color, :name, :sex, :description, presence: true
  validates :color, inclusion: { in: COLORS, 
    message: "Choose a standard color" }
  validates :sex, inclusion: { in: %w(M F),
    message: "Choose either M or F" } 
    
  has_many :cat_rental_requests,
    primary_key: :id,
    foreign_key: :cat_id,
    class_name: :CatRentalRequest,
    dependent: :destroy
end

cats_99/app/models/cat_rental_request.rb
class CatRentalRequest < ApplicationRecord
  validates :cat_id, :start_date, :end_date, :status, presence: true
  validates :status, inclusion: { in: %w(APPROVED DENIED PENDING),
  message: "Choose either APPROVED, DENIED, OR PENDING"}
  
  belongs_to :cat,
    primary_key: :id,
    foreign_key: :cat_id,
    class_name: :Cat
    
  def overlapping_requests
    start_date1= self.start_date.dup 
    end_date1 = self.end_date.dup
    CatRentalRequest.where(cat_id: self.cat_id).where(start_date BETWEEN start_date1 AND end_date1)
    
    CatRentalRequest.where.not(id: self.id)
    .where(cat_id: cat_id)
    .where.not('start_date > :end_date or end_date < :start_date',start_date: start_date, end_date: end_date)
  end 
end

cats_99/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

cats_99/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index 
    @cats = Cat.all
    render :index
  end 
  
  def show 
    @cats = Cat.find(params[:id])
    
    if @cats 
      render :show
    else 
      redirect_to cats_url
    end 
  end 
  
  def new 
    @cat = Cat.new()
    render :new 
  end 
  
  def create 
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cat_url(@cat) 
    else 
      render :new
    end 
  end 
  
  def update
    @cat = Cat.find(params[:id])
    
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else 
      render json: @cat.errors.full_messages, status: 422
    end 
  end 
  
  def edit 
    @cat = Cat.find(params[:id])
    if @cat
      render :edit
    else 
      redirect_to cats_url 
    end 
  end 
  
  private 
  def cat_params
    params.require(:cat).permit(:birth_date, :color, :name, :sex, :description)
  end 
end 

cats_99/app/helpers/application_helper.rb
module ApplicationHelper
end

cats_99/app/views/cats/_form.html.erb
<form <% if type == :new %>
   action=" <%= cats_url %>"
   <% elsif type == :edit %>
    action="<%= cat_url(cat) %>"
    <% end %>
   
   
   method="Post">
  <% if type == :edit %>
    <input type = "hidden" name ="_method" value = "Patch">
  <% end %>
  <label for ="name">Name</label>
  <input id= "name" type= "text" name='cat[name]' value="<%= cat.name %>">
  <br>
  <br>
  
  <label for ="sex">Sex: </label>
  <% if cat.sex == "M" %>
    M<input checked type = "radio" name="cat[sex]" value ="M">
    F<input type = "radio" name="cat[sex]" value ="F">  
  <% elsif cat.sex == "F" %>
    M<input type = "radio" name="cat[sex]" value ="M">
    F<input checked type = "radio" name="cat[sex]" value ="F"> 
  <% else %> 
    M<input type = "radio" name="cat[sex]" value ="M">
    F<input type = "radio" name="cat[sex]" value ="F">  
  <% end %>

  
  <br>
  <br>
  
  <label for "color">Color: </label>
  <select name = "cat[color]">
    <option disabled selected> --Select Color-- </option>
    <% Cat::COLORS.each do |color| %>
      <% if cat.color == color %>
        <option selected value = '<%= color %>'> <%= color %> </option>
      <% else %>
        <option value = '<%= color %>'> <%= color %> </option>
      <% end %>
    <% end %>
  </select>
  <br>
  <br>
  
  <label for "birth_date">Birth Date: </label>
  <input type='date' id='birth_date' name = 'cat[birth_date]' value="<%= cat.birth_date %>">
  <br>
  <br>
  
  <label for "description">Description:  </label>
  <textarea name='cat[description]'><%= cat.description %></textarea>
  <br>
  <br>
  
  <input type="hidden" name= "authenticity_token" value= "<%= form_authenticity_token %>">
  
  <input type='submit' 
  <% if type == :new %> 
    value="Add New Cat">
  <% else %>
    value='Save Cat'>
  <% end %>
  
</form>

cats_99/app/views/cats/edit.html.erb
<h1> EDIT DA OLD CAT </h1>
<br>
<br>

<%= render 'form', cat: @cat, type: :edit%>

cats_99/app/views/cats/index.html.erb
<h1> Hay Look at these cats</h1>

<% @cats.each do |cat| %>
<ul>
  <li><strong>Name:</strong> <a href="<%= cat_url(cat.id)%>"><%= cat.name %></a></li>
  <br>
</ul>
<% end %>

cats_99/app/views/cats/new.html.erb
<h1> MAKE DA NEW CAT </h1>
<br>
<br>

<%= render 'form', cat: @cat, type: :new%>

cats_99/app/views/cats/show.html.erb
<h1> CHECK OUT THIS DOPE CAT </h1>

<table>
  <thead>
    <tr>
      <th colspan="2"> <%= @cats.name %></th>
    </tr>
  </thead>
  <tbody>
      <tr>
        <td>Birth Date:</td>
        <td> <%= @cats.birth_date %></td>
      </tr> 
      <tr>
        <td>Color:</td>
        <td> <%= @cats.color %></td>
      </tr> <tr>
        <td>Sex:</td>
        <td> <%= @cats.sex %></td>
      </tr> <tr>
        <td>Description:</td>
        <td> <%= @cats.description %></td>
      </tr> 
    </tbody>
  </table>
  <form action= "<%= edit_cat_url(@cats) %>" method= "get">
    <input type="submit" value="Edit Cat">
  </form>
<!-- <ul>
  <li><strong>Name:</strong> <%#= @cats.name %></li>
  <li><strong>Birth Date:</strong> <%#= @cats.birth_date %></li>
  <li><strong>Color:</strong> <%#= @cats.color %></li>
  <li><strong>Sex:</strong> <%#= @cats.sex%></li>
  <li><strong>Description:</strong> <%#= @cats.description %></li>
  <br>
</ul> -->

cats_99/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats99</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>